sudo: false
language: c

deploy:
  provider: s3
  access_key_id: AKIAIAVQAXMLLEPM4I5A
  secret_access_key:
    secure: "Wfc6T/RRTTcBgL7bPGBUDK09FQR1Zeut4JD+Yr+l4iMcYcr86HPu8qID83mRUR5gfFU97r+tDeRZ+uZAOwhgoyVO+wD8vljsxQ7sLJ8z505vvxw8B75g39sCF46I2JBu9NqemqAo8+ihq9uW3g7qdT7vZEGpuZIp12Sq/Ik1dko="
  bucket: stackage-travis
  acl: public_read
  skip_cleanup: true
  local_dir: to-travis
  upload-dir: hackage-mirror
  on:
    repo: fpco/hackage-mirror
    branch: master

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.3.1/stack-0.1.3.1-x86_64-linux.gz | gunzip > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack
- stack --no-terminal setup

script:
- mkdir -p to-travis
- stack --no-terminal build --copy-bins --local-bin-path to-travis
- stack --no-terminal test
- bzip2 to-travis/hackage-mirror

cache:
  directories:
  - $HOME/.stack
