sudo: false
language: c

deploy:
  provider: s3
  access_key_id: AKIAIAVQAXMLLEPM4I5A
  secret_access_key:
    secure: "Wfc6T/RRTTcBgL7bPGBUDK09FQR1Zeut4JD+Yr+l4iMcYcr86HPu8qID83mRUR5gfFU97r+tDeRZ+uZAOwhgoyVO+wD8vljsxQ7sLJ8z505vvxw8B75g39sCF46I2JBu9NqemqAo8+ihq9uW3g7qdT7vZEGpuZIp12Sq/Ik1dko="
  bucket: stackage-travis
  acl: public_read
  skip_cleanup: true
  local_dir: to-travis
  upload-dir: hackage-mirror
  on:
    repo: fpco/hackage-mirror
    branch: master

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- mkdir -p to-travis
- stack --no-terminal build --copy-bins --local-bin-path to-travis
- stack --no-terminal test
- bzip2 to-travis/hackage-mirror
- bzip2 to-travis/hackage-watcher

cache:
  directories:
  - $HOME/.stack
